### ISSUE TITLE
Support for Proxying URLs for Use in Client Side? 

### ISSUE THREAD

**Issue by ultamatt** [RIAEvangelist/node-dominos-pizza-api#111]
While tooling around with this library (Thanks btw!) I found that I could not effectively use it in a User Interface because of the CORS Same Origin Requirements. Suffice it to say that it is unreasonable to ask Dominos to pass the appropriate header variable, however [I believe I can proxy the requests and fudge the missing CORS stuff.. 
](https://github.com/Rob--W/cors-anywhere/)

See My janky UI here with CORS unhappiness. I also tried to stand this up on my Digital Ocean droplet with the same CORS result. 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/2548904/115506930-500b9b80-a230-11eb-92a6-aa07d7a75f86.png">

To do that I need to change around the URL you are using to talk to dominos to send to my proxy and not dominos itself. [Soooo I forked this repo and tried to mock out a guess on implementation. ](https://github.com/RIAEvangelist/node-dominos-pizza-api/compare/master...ultamatt:master)

I think my approach could use some guidance, and while I could just fork the library and make it dance to my flavor of tune, I imagine that someone else might be looking at this and thinking the exact same thing. 

Thoughts?

**Comment by RIAEvangelist** [comment]
I see 2 possible ways of doing this:

1) do it the standard way, which is to put your implementation of the dominas calls on your DO droplet, and then make API requests from your UI to your Dominos implementation, this could make your front end very simple, and have most of the logic on the back end. This would be the best practice way of doing it, and CORS is not an issue this way as I have already handled it all for you.

2) you could use my `node-http-server` module to do the straight up proxy calls. Then Cors is not an issue.
When doing this you would follow the Internationalization process and just swap all the calls in the URLs object to point at your server instead.

I strongly recommend route 1 but both ways will work.

**Comment by RIAEvangelist** [comment]
LMK if this helps, or if you need some more guidance, otherwise I will close the question.

**Comment by ultamatt** [comment]
Hi there, just saw your reply. Thank you very much. 

I ended up re-reading how you're handling URLs and realized I could co-opt your 'internationalization' work into using my proxy URL more cleanly. 

```
import { urls } from 'dominos';
import { useInternational as changeUrls, canada } from 'dominos/utils/urls.js';
import { host } from './urlService';

const proxyPrefix = `http://${host}:6643/`;

const proxiedUrls = {
  sourceUri : urls.sourceUri,
  location:{
    find: proxyPrefix + urls.location.find
  },
  store : {
    find : proxyPrefix + urls.store.find,
    info : proxyPrefix + urls.store.info,
    menu : proxyPrefix + urls.store.menu
  },
  order: {
    validate: proxyPrefix + urls.order.validate,
    price: proxyPrefix + urls.order.price,
    place: proxyPrefix + urls.order.place,
  },
  images: proxyPrefix + urls.images,

  trackRoot: proxyPrefix + urls.trackRoot,
  track: proxyPrefix + urls.track,

  //POST {storeId: "8278"}
  token: proxyPrefix + urls.token,

  //POST general upsell see below
  upsell: proxyPrefix + urls.upsell,

  //POST specific types of upsell see below
  stepUpsell: proxyPrefix + urls.stepUpsell,
};

changeUrls(proxiedUrls);
```

I ended up standing up a simple proxy backend. This is mostly a front end exercise for me. 

Also, I'm now onto the validation step. Using your application I was unable to appropriately validate my order. I ended up jumping onto the dominos site and ordering myself some pizza (hungry developers make bugs). It's looking like I'm getting these errors from my version of the validation 

Here's my post using your library. (Pepperoni and Mushroom forever!) The address form being so blank is suspicious to me... 
```
{
	"Order": {
		"Address": {
			"City": "",
			"DeliveryInstructions": "",
			"PostalCode": "91607",
			"Region": "",
			"Street": "",
			"StreetName": "",
			"StreetNumber": "",
			"UnitNumber": "",
			"UnitType": ""
		},
		"Amounts": {},
		"AmountsBreakdown": {
			"adjustment": "0.00",
			"bottle": 0,
			"cash": 0,
			"customer": 0,
			"deliveryFee": "0.00",
			"foodAndBeverage": "0.00",
			"roundingAdjustment": 0,
			"savings": "0.00",
			"surcharge": "0.00",
			"tax": 0,
			"tax1": 0,
			"tax2": 0,
			"tax3": 0,
			"tax4": 0,
			"tax5": 0
		},
		"BusinessDate": "",
		"Coupons": [
			9193
		],
		"Currency": "",
		"CustomerID": "",
		"Email": "ultamatt@gmail.com",
		"EstimatedWaitMinutes": "",
		"Extension": "",
		"FirstName": "Matt",
		"HotspotsLite": false,
		"IP": "",
		"LanguageCode": "en",
		"LastName": "Moeller",
		"Market": "",
		"metaData": {
			"calculateNutrition": true,
			"contactless": true
		},
		"NewUser": true,
		"NoCombine": true,
		"OrderChannel": "OLO",
		"OrderID": "",
		"OrderInfoCollection": [],
		"OrderMethod": "Web",
		"OrderTaker": "node-dominos-pizza-api",
		"Partners": {},
		"Payments": [],
		"Phone": "4075555555",
		"PhonePrefix": "",
		"PriceOrderMs": 0,
		"PriceOrderTime": "",
		"Products": [
			{
				"Code": "12SCREEN",
				"ID": 1,
				"isNew": true,
				"Options": {
					"M": {
						"1/1": "1"
					},
					"P": {
						"1/1": "1"
					},
					"X": {
						"1/1": "1"
					}
				},
				"Qty": 1
			},
			{
				"Code": "12SCREEN",
				"ID": 2,
				"isNew": true,
				"Options": {
					"M": {
						"1/1": "1"
					},
					"P": {
						"1/1": "1"
					},
					"X": {
						"1/1": "1"
					}
				},
				"Qty": 1
			},
			{
				"Code": "12SCREEN",
				"ID": 3,
				"isNew": true,
				"Options": {
					"M": {
						"1/1": "1"
					},
					"P": {
						"1/1": "1"
					},
					"X": {
						"1/1": "1"
					}
				},
				"Qty": 1
			}
		],
		"Promotions": {},
		"PulseOrderGuid": "",
		"ServiceMethod": "delivery",
		"SourceOrganizationURI": "order.dominos.com",
		"StoreID": "7897",
		"Tags": {},
		"UserAgent": "",
		"Version": "1.0"
	}
}
```

And here's the status items I'm getting back from them. 
```
{
	"StatusItems": [
		{
			"Code": "AutoAddedOrderId"
		},
		{
			"Code": "PriceInformationRemoved"
		},
		{
			"Code": "ServiceMethodNotAllowed"
		}
	]
}
```

I realize that now I may be abusing the 'issue' system here in github and that you'd likely want to keep your project cleaned up. I really appreciate the work that's gone into this API and thank you very much.

**Comment by RIAEvangelist** [comment]
Nah, you are fine. This would have been better under [discussions](https://github.com/RIAEvangelist/node-dominos-pizza-api/discussions), but now you actually have a legit question.

I think the keys are the address looks empty, and `"Code": "ServiceMethodNotAllowed"`

I am thinking store `"StoreID": "7897",` was not allowing `delivery` when you placed the order. Remember the store needs to be open and delivering to your area to validate otherwise it legit, will not validate.  You can also try `carryout` I think the options are documented somewhere... lol Maybe the [`/docs/Order.md`](https://github.com/RIAEvangelist/node-dominos-pizza-api/blob/master/docs/Order.md#instance-public-fields) under publicMembers `.serviceMethod` It could also be as simple as the service method being lowercase in your code, not sure. My docs have them all `pascal case`

**Comment by RIAEvangelist** [comment]
Is this still an issue or should this be closed?

**Comment by ultamatt** [comment]
Let me check it out again this weekend and get back to you. I'm buried at work at the moment. Is that okay with you?

**Comment by RIAEvangelist** [comment]
sounds good!
