### ISSUE TITLE
Dominos Pizza CLI

### ISSUE THREAD

**Issue by alestor123** [RIAEvangelist/node-dominos-pizza-api#112]
I think i can work on dominos cli but i need some clearance

**Comment by alestor123** [comment]
need the approval @RIAEvangelist

**Comment by RIAEvangelist** [comment]
Would be awesome! 🎉

**Comment by alestor123** [comment]
But i will hosting it as another npm module

**Comment by alestor123** [comment]
@RIAEvangelist

**Comment by RIAEvangelist** [comment]
There is already a CLI in the examples and this module is set up to run a CLI inside of it.

If you want to build your own, as a separate module, you do not need my approval. This is open source, you can do what you want.

If you want to contribute to this module, which would get you more exposure and listed as a contributor, then, you should contribute it to this code base.

Either way is OK with me though, that is what open source is all about.
