### ISSUE TITLE
Please Lable  It Unofficial

### ISSUE THREAD

**Issue by alestor123** [RIAEvangelist/node-dominos-pizza-api#114]
I think we should lable the project as unofficial

**Comment by alestor123** [comment]
@RIAEvangelist i think it could cause some problems

**Comment by RIAEvangelist** [comment]
I disagree. This project has been up for many years, and there is no official api.

**Comment by Heath123** [comment]
There's no reason not to clarify it, the README makes it sound official

**Comment by RIAEvangelist** [comment]
Ok.

**Comment by madelinecameron** [comment]
Dominos is _extremely_ unlikely to make an official API. 

When I last worked on it, Dominos Engineering is well aware of the project and gives tacit approval of these kinds of projects.
