### ISSUE TITLE
Cash On Delivery

### ISSUE THREAD

**Issue by alestor123** [RIAEvangelist/node-dominos-pizza-api#116]
hey can we have cash on delivery option @RIAEvangelist

**Comment by RIAEvangelist** [comment]
I believe there is already support for this, but I have not documented it yet. You should order a pizza from the dominos website using cash as the payment option. Look at the payloads in the console, and see where Cash is used.

I think this would be in the Payment object or the address object under service method. 

But you will have to check on the dominos website to confirm.

**Comment by alestor123** [comment]
@RIAEvangelist  I think you should document it

**Comment by alestor123** [comment]
@RIAEvangelist  How do i put cash on deplivery

**Comment by mattcroat** [comment]
> @RIAEvangelist How do i put cash on deplivery

This might be helpful [How I Ordered A Pizza With VSCode](https://www.youtube.com/watch?v=qIrEwrMHU0M) as they use cash on delivery. You can also look at the [source code](https://github.com/WebDevSimplified/vscode-extension-pizza/blob/main/src/steps.ts).

**Comment by alestor123** [comment]
@mattcroat nope its using card im working on it

**Comment by alestor123** [comment]
I think we can do it by leaving the payments with  empty string

**Comment by mattcroat** [comment]
I figure this would be simple as doing (the Dominos API already supports it):
```js
const payment = new Payment({ amount: order.amountsBreakdown.customer })

payment.type = 'Cash'

order.payments.push(payment)
```

**Comment by Heath123** [comment]
Imagine doing that in a loop with every address in the world... (you'd get ratelimited but still, the fact that Dominoes allows that is a little worrying)

**Comment by RIAEvangelist** [comment]
@Heath123 I updated your comment. You are 100% correct and I did what you are thinking about. I also reported it to dominos.

I feel the same as you, but none the less I do not want to put that thought out there because that hole goes pretty deep and could result in sad things happening. I like to promote only happy things.

Let's 🍕 for good ok!

**Comment by Heath123** [comment]
Ah, I guess I could give bad people ideas, sorry

**Comment by RIAEvangelist** [comment]
@Heath123 NP, I have worked on a lot of security-related stuff including Class 3 medical devices that are permanently implanted in humans' bodies, so seeing these sorts of things comes naturally to me at this point. It took some self-training to make it automatic though. Thanks for being cool with me editing your post.
