### ISSUE TITLE
The NearbyStores function doesnt work

### ISSUE THREAD

**Issue by SebastianMostert** [RIAEvangelist/node-dominos-pizza-api#122]
```js
import {NearbyStores} from '../index.js';

const nearbyStores=await new NearbyStores('110 S Fairfax Ave, 90036');

console.dir(nearbyStores,{depth:5});

console.log('\n\nFirst store in the list');
console.dir(nearbyStores.stores[0],{depth:0});
```
C:\Users\mosse\Downloads\node-dominos-pizza-api-master\node-dominos-pizza-api-master\node_modules\node-fetch\lib\index.js:1461
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
                               ^
FetchError: request to https://order.dominos.com/power/store-locator?s=110%20S%20Fairfax%20Ave&c=%20%2090036&type=Delivery failed, reason: connect ETIMEDOUT 209.211.200.20:443
    at ClientRequest.<anonymous> (C:\Users\mosse\Downloads\node-dominos-pizza-api-master\node-dominos-pizza-api-master\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (node:events:394:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by RIAEvangelist** [comment]
Looks like you timed out, were you making a lot of requests?

**Comment by odog2454** [comment]
I seem to be getting a similar error
![image](https://user-images.githubusercontent.com/99774180/166842304-ce0a0fd8-5ca3-45cf-b856-5d3faf5c37cc.png)

**Comment by odog2454** [comment]
From running this
![image](https://user-images.githubusercontent.com/99774180/166842622-04b135f1-1975-4972-917c-1f31a669c20f.png)

**Comment by odog2454** [comment]
And like I have tried a large number of different types of addresses

**Comment by odog2454** [comment]
After further investigation I found that the request is getting denied and returning HTML which causes the error. Do you know why this might be happening?
![image](https://user-images.githubusercontent.com/99774180/166848972-ebdb539a-1c52-4e81-b1c3-c127da6ec7a8.png)

**Comment by odog2454** [comment]
I think this is occuring because I'm in New Zealand. I have seen the bit in the docs on adding international urls but do you know how I would go about finding all the urls needed for New Zealand?

**Comment by RIAEvangelist** [comment]
Hey Oscar. Just caught up on your logs here. Thanks for all the info! It
really helps me understand what you are experiencing and how I can help!

My first suggestion would be to look at the internationalization examples
as you mentioned you have and then open up the console on the NZ Domino's
site. Watch the requests being made and inspect the urls. It's most likely
going to be a simple change in the pattern. Once you find what needs to
change, you can make a new file for NZ and we can get it updated!

Good luck! And let me know if you need to do a Google meet or something.

Best,

Brandon

**Comment by odog2454** [comment]
Thanks for the detailed response Brandon!
