### ISSUE TITLE
Question: How can I test this API on windows?

### ISSUE THREAD

**Issue by bobmartins79** [RIAEvangelist/node-dominos-pizza-api#126]
Hi guys,

Sorry, this is probably not the best place for questions, but I'm learning to program, and I would like to know if you can recommend how to install the required environment to run this API in an old machine with Windows XP SP II. is it possible?

Thanks in advance, especially to @RIAEvangelist, the genius behind this great library.
 I appreciated your excellent work as an open-source contributor.

**Comment by RIAEvangelist** [comment]
If node runs on your system, that's all you need. Let me know anywhere the docs are not clear.
