### ISSUE TITLE
order.price() fails with any order. 

### ISSUE THREAD

**Issue by Nestrixx** [RIAEvangelist/node-dominos-pizza-api#128]
I have tried all of the example listed order items in the documentation such as `code: 'P_14SCREEN'`, and  order.price() throws `DominosPriceError` 
![image](https://user-images.githubusercontent.com/47996825/155256625-bf2e5559-29e6-461a-af35-e78a2347a592.png)
The only changes to the TLDR version of the code that I made is changing the `order.serviceMethod` to `Carryout` and removed the `store.IsDeliveryStore` check, as in our case we don't care about delivery. 

`order.Validate` passes and I have tried multiple addresses such as '2928 1st Ave, Seattle, WA 98121'.

**Comment by ElijahPepe** [comment]
Receiving the same error. The issue is probably the code in the pizza constant.

**Comment by RIAEvangelist** [comment]
This is just because the 14SCREEN is deprecated I think. Have to look at the new menu items.

**Comment by RIAEvangelist** [comment]
BTW, I am pretty sure I updated the docs.
