### ISSUE TITLE
Stop supporting RIAEvangelist 

### ISSUE THREAD

**Issue by KristN1** [RIAEvangelist/node-dominos-pizza-api#130]
This guy is seriously just milking the war pretty badly, I've forked the peacenotwar on github but unfortunately prs are blocked there so I hope he gets a notification here  @RIAEvangelist 

# peacenotwar

This package is only here to give the author publicity which is also proven by the fact it is released under GPL-3.0 meaning you have to explicitly say you're using this package. This repository als has issues/PRs limited to avoid any drama and issues.

*Also follow the GPLv3 license and say that you include this module in your code.* - `README.md`

Instead of using it, you should consider donating to any charity which will directly support the people of Ukraine, you can donate on https://savelife.in.ua/en/ or find a charity of your choice, there are plenty. 

Also please think twice before using & supporting a module such as this thus giving free publicity to the author and instead think about supporting other open-source developers that are behind some of the apps you are using in your day-to-day life

**Comment by RIAEvangelist** [comment]
Krist you don't know what you are talking about.

**Comment by RIAEvangelist** [comment]
That said, the other charity is good. People should donate.
