### ISSUE TITLE
Address Test suite should pass

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-dominos-pizza-api#22]
Address

    1) should create Address object from JSON
    ✓ should create Address object from string
    ✓ should return full address to pass to findNearbyStores
    2) should return zip code to pass to findNearbyStores
    3) should return city, state, zip to pass to findNearbyStores
    ✓ should create Address object from array

**Comment by madelinecameron** [comment]
What's the errors? Mine is passing those just fine.

**Comment by madelinecameron** [comment]
It looks like you might have an older version of teh code because I know the failing test #2 and #3 are ones that were failing until I made a change recently. I believe all of my changes have been pushed into PizzaPI (both the branch and my own repository, although I am using only the branch now)

**Comment by RIAEvangelist** [comment]
FYI, you know if you work in this repo, you can  do a git fetch upstream to update your repo, right?

**Comment by RIAEvangelist** [comment]
Lets review the Address Class from commit 6f4b8f3

I think it is a very transparent method, and keeps scoping very clean.
