### ISSUE TITLE
refactor getMenu

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-dominos-pizza-api#32]
need to apply some data massaging so that the Code on Products is the one we send.

perhaps create a separate menu of pizzapi.Item's which can just be added to the order with minimal thought.

**Comment by RIAEvangelist** [comment]
@julianh2o if you have any ideas we can track the convo here.

**Comment by julianh2o** [comment]
Our current Item class encapsulates a "shopping cart item" and it combines a product (code), a quantity, and options.. A menu item obviously doesn't include quantity and options.. I'm thinking we may want to implement a new class MenuItem to represent this. Thoughts?

**Comment by RIAEvangelist** [comment]
seems like this is working
