### ISSUE TITLE
modules in git history

### ISSUE THREAD

**Issue by Machyne** [RIAEvangelist/node-dominos-pizza-api#4]
`node_modules` should be ignored.

As it stands, I'm getting errors with `xml2json` dependency thats version controlled in this repository. Removing the node_modules folder and reinstalling fixes this.

I'd be happy to send a PR with this update if you'd like.
-Matt

**Comment by RIAEvangelist** [comment]
Please do :)

since you found and fixed it it would be nice to show your contribution.

**Comment by RIAEvangelist** [comment]
needs to be fixed again

**Comment by RIAEvangelist** [comment]
fixed
