### ISSUE TITLE
Phone Number is never set

### ISSUE THREAD

**Issue by bhberson** [RIAEvangelist/node-dominos-pizza-api#42]
In the order object `Phone` is declared, but never set, so the phone number is always empty.

**Comment by madelinecameron** [comment]
Haha, I noticed this too. Never got around to fixing it.

Thanks!

**Comment by julianh2o** [comment]
Fixed by https://github.com/RIAEvangelist/node-dominos-pizza-api/pull/41 in hotfixes branch
