### ISSUE TITLE
Error in StatusItems: [{'Code': 'CreditCardPaymentNotAllowed'}]

### ISSUE THREAD

**Issue by Melvillian** [RIAEvangelist/node-dominos-pizza-api#53]
What is the reason for Domino's servers returning the above error?

I am using node-dominos-pizza-api to, well, order some pizza. I'm within the United States and am using valid billing and personal data. I have tried several different credit cards, yet all return this error. I'd appreciate any guidance on why this error is occurring and what I can do to prevent it from happening.

**Comment by RIAEvangelist** [comment]
Can you paste a code snippit, or is your project up on github?

**Comment by anthonyseo** [comment]
having the same issue.

{ Address: 
   { Type: 'House',
     Street: '/*DELETED*/',
     City: '/*DELETED*/',
     Region: '/*DELETED*/',
     PostalCode: '/*DELETED*/' },
  Coupons: [],
  CustomerID: '',
  Email: '/*DELETED*/',
  Extension: '',
  FirstName: '/*DELETED*/',
  LastName: '/*DELETED*/',
  LanguageCode: 'en',
  OrderChannel: 'OLO',
  OrderID: '',
  OrderMethod: 'Web',
  OrderTaker: null,
  Payments: 
   [ { Type: 'CreditCard',
       Number: '/*DELETED*/',
       CardType: '/*DELETED*/',
       Expiration: '/*DELETED*/',
       SecurityCode: '/*DELETED*/',
       PostalCode: '/*DELETED*/' } ],
  Phone: '/*DELETED*/',
  Products: 
   [ { AutoRemove: false,
       Code: '14SCREEN',
       Qty: 1,
       ID: 1,
       isNew: true,
       Options: [Object] } ],
  Market: 'UNITED_STATES',
  Currency: 'USD',
  ServiceMethod: 'Delivery',
  SourceOrganizationURI: 'order.dominos.com',
  StoreID: '/*DELETED*/',
  Tags: {},
  Version: '1.0',
  NoCombine: true,
  Partners: {},
  NewUser: true,
  metaData: {},
  Amounts: {},
  BusinessDate: '',
  EstimatedWaitMinutes: '',
  PriceOrderTime: '',
  IP: '/*DELETED*/',
  Status: -1,
  StatusItems: [ { Code: 'CreditCardPaymentNotAllowed' } ],
  Promotions: { Redeemable: [], Valid: [] } }

**Comment by RIAEvangelist** [comment]
` 14SCREEN ` isn't a valid order any more.

you have to look inside the object to see what it contains. Domino's no longer supports their quick codes. I think there was another issue about this somewhere.

Soooo... they supply those codes along with everything you would need to order them. Go figure.

**Comment by mulka** [comment]
I'm also getting this error. How do you order stuff if not with the codes? Could you update the documentation on how to do that?
