### ISSUE TITLE
Error when using dominos CLI

### ISSUE THREAD

**Issue by dineshraj** [RIAEvangelist/node-dominos-pizza-api#54]
I've just downloaded the project from the website and tried using the CLI, I used the command `full menu for closest 63102`

However, after a few mins, I get the following error: 

```
commandline-pizza/dominos-commandline-pizza.js:280
            order.Address=new pizzapi.Address(storeData.result.Address);
                                                              ^

TypeError: Cannot read property 'Address' of undefined
```

Do you know why this is?

**Comment by RIAEvangelist** [comment]
This looks like another outcome of #56
