### ISSUE TITLE
Are UK Domino stores supported? 

### ISSUE THREAD

**Issue by dineshraj** [RIAEvangelist/node-dominos-pizza-api#55]
I'm from the UK and currently writing a node app for handling / simplifying group orders - would this API work for our stores ? 

If it helps, the menu for a store seems to be returned from a call like this: 

https://www.dominos.co.uk/Tracking/ListingProductsDisplayed?productIds=1500%7C15%7C18%7C17%7C24%7C1046%7C55%7C13%7C1052%7C14%7C1358%7C56%7C39%7C1474%7C23%7C34%7C59

It seems to use a cookie to determine your location for the menu though

**Comment by madelinecameron** [comment]
Likely not since the urls in urls.json inside /src points to the US urls rather than UK urls. 

This should be easily fixable by replacing the urls with the corresponding urls from the UK version, this is given that they have the same endpoints exposed (which in some non-US versions is not true).

**Comment by dineshraj** [comment]
Yea, I saw that upon further exploration of the app. Thanks!

**Comment by RIAEvangelist** [comment]
I wonder if the API is the same though?

If so we could add it in pretty easily.

**Comment by safinn** [comment]
It seems to be different. The store finder URL is `https://www.dominos.co.uk/storefindermap/storesearch?SearchText=${post code}`

That gets me the store ID but not sure how to get to the point of making the order.

**Comment by RIAEvangelist** [comment]
Sweet info.
