### ISSUE TITLE
Running pizzapi inside my node app gives me a timeout

### ISSUE THREAD

**Issue by dineshraj** [RIAEvangelist/node-dominos-pizza-api#56]
My code at the moment is basically this 

```
var pizzapi = require('pizzapi');

var app = express();

pizzapi.Util.findNearbyStores(
    '90210',
    'Delivery',
    function(storeData){
        console.log('data: ', storeData);
    }
);
```

However in the command line I get the following error.. 

```bash
data:  { success: false,
  message:
   { [Error: connect ETIMEDOUT 205.218.22.12:443]
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '205.218.22.12',
     port: 443 } }
```

Do you know why this would happen?

**Comment by RIAEvangelist** [comment]
Thats a legit timeout if you go to the address it is not available.

[Click Me HTTP case](http://205.218.22.12:443)

[Click Me HTTPS case](http://205.218.22.12:443)

**Comment by dineshraj** [comment]
Yes true, but I was under the impression that this module should work out of the box? Why is it timing out, what IP is it trying to connect to?

**Comment by RIAEvangelist** [comment]
Is that the production setting??

huh should be orders.dominos.com or something similar.

**Comment by RIAEvangelist** [comment]
There is no refrence to : 205.218.22.12 in the code

**Comment by dineshraj** [comment]
The IP does seem to point to Dominos when doing a WHOIS lookup: 

http://whois.domaintools.com/205.218.22.12

**Comment by 4m4rOk** [comment]
Looks like Dominos is rerouting everyone accessing orders.dominos.com from outside the US.

**Comment by RIAEvangelist** [comment]
:+1: 

@4m4rOk are you looking for local access?

**Comment by 4m4rOk** [comment]
At the moment I'm running a server in the US, which is enough to play around with your wrapper a bit.
I might have a look at Europe later though!

_Slightly off-topic: Do you know if Domino's have a rather aggressive flood control in place?_

**Comment by RIAEvangelist** [comment]
@4m4rOk ***yes*** they do have very aggressive anti DOS in place. They will block you for about 15 min.

It's kind of like this :

![blocked](http://img.gawkerassets.com/img/19f4jjkecmnbhgif/original.gif)

**Comment by johnhforrest** [comment]
@RIAEvangelist Do you have any details on the limits of the API? Is there a key system in place with Dominos to prevent hitting the limit? Would love to hear more about this.
