### ISSUE TITLE
Dominos Canada support

### ISSUE THREAD

**Issue by rolandsoft** [RIAEvangelist/node-dominos-pizza-api#57]
Hi, I was wondering if there can be a Dominos Canada fork... would love to be able to automate my weekly orders... also if it supports the coupon system (Mondays is 50% off using MON50P coupon)

**Comment by madelinecameron** [comment]
It does support coupons last time I checked, at least in the US. 

As long as Dominos Canada uses the same endpoints and has them exposed, it should work exactly as expected.
 
I don't think we have a tutorial explaining how to add coupons, but I believe there was a PR that added methods for adding coupons. It is just a key inside of the Order object.

**Comment by rolandsoft** [comment]
I wasn't able to see the Dominos.com website from Canada, but using hola I was able to browse the US site, and it looks like the same, I'll try it this weekend and see if I can get it working... will post if successful

**Comment by James-Firth** [comment]
@rolandsoft Any results for Canada?

**Comment by RIAEvangelist** [comment]
Does anyone know the canadian api address?

**Comment by johnhforrest** [comment]
I took a look at some of the urls in urls.json and I think it's easy to just substitute the TLD (notice .ca instead of .com).

e.g.,:

https://order.dominos.ca/power/store-locator
https://order.dominos.ca/power/store/
https://order.dominos.ca/power/price-order

**Comment by pdube** [comment]
Opened up a PR for this. It works for Canada as well now

**Comment by RIAEvangelist** [comment]
Thanks @pdube merged. Gonna do one more run through and release tonight.
