### ISSUE TITLE
Can I place an order without a payment?

### ISSUE THREAD

**Issue by austinhuang0131** [RIAEvangelist/node-dominos-pizza-api#66]
Like, let it collect payment upon delivery?

**Comment by RIAEvangelist** [comment]
If you can get Domino's to bring you a pizza without paying first I will be
amazed. Generally I think they do not allow this to prevent pranks.

**Comment by yazeedalrubyli** [comment]
In Saudi Arabia, We can pay in cash either for delivery or carryout. Check it out https://www.dominos.sa
