### ISSUE TITLE
TypeError: order.PaymentObject is not a function

### ISSUE THREAD

**Issue by evblurbs** [RIAEvangelist/node-dominos-pizza-api#71]
When I run the code

`var cardInfo = new order.PaymentObject();`

I get the error

`TypeError: order.PaymentObject is not a function`

Is this due to the order object not being complete? Does the payment object still work? Thanks in advance!

**Comment by RIAEvangelist** [comment]
Would need more info. For example, what is order? How did you initalize it? 

Why are you trying to create a new instance of the value returned from something which is not a function? (You are executing the Payment Object as if it were a function...)
