### ISSUE TITLE
Unable to place an order with multiple items

### ISSUE THREAD

**Issue by benhubsch** [RIAEvangelist/node-dominos-pizza-api#72]
Hi! I'm experiencing an issue where putting multiple Items in an order doesn't work -- the order is priced at 0 dollars (despite being priced) and I'm told that it'll take 0 minutes for the order to be delivered. Any thoughts on why? For now, just doing hardcoded: 

         `orderObj.addItem(new pizzapi.Item(
                {
                    code: 'S_PIZPH',
                    options: [],
                    quantity: 1
                }
            ))

            orderObj.addItem(new pizzapi.Item(
                {
                    code: 'S_PIZZA',
                    options: [],
                    quantity: 1
                }
            ))`

**Comment by RIAEvangelist** [comment]
:rofl: no, but thats a damn good delivery time. hope to take a look at this sometime soon.

**Comment by RIAEvangelist** [comment]
just want to confirm this is still an issue?

**Comment by benhubsch** [comment]
Yeah, still is. I think the menu item codes might be deprecated?

**Comment by RIAEvangelist** [comment]
I think this is related to #85
