### ISSUE TITLE
TypeError: Cannot read property 'Variants' of undefined

### ISSUE THREAD

**Issue by superamario64** [RIAEvangelist/node-dominos-pizza-api#78]
Using [Runkit](https://runkit.com), I'm trying to return a JSON of a menu of my local Domino's. It's returning this instead: `{}` So I checked the endpoint logs and there's this error:
```
TypeError: Cannot read property 'Variants' of undefined
 in pizzapi/src/Store.js — line 62

var variantKeys = Object.keys(result.result.Variants)
```
You can see the full code here: https://runkit.com/levistep32/5b8a05f1ed7d5b0012a8ecec

**Comment by RIAEvangelist** [comment]
`result.result` is not defined in the scope you are trying to use it in. Maybe just try `result`.
