### ISSUE TITLE
Menu Items Not Ordering

### ISSUE THREAD

**Issue by batesr99** [RIAEvangelist/node-dominos-pizza-api#80]
I have attempted to order something that is not the default cheese pizza (14SCREEN) and cannot figure out why the order is not being priced and placed. As an example, I'm ordering a pepperoni mushroom pizza (MPXC_12SCREEN), the order is priced and placed as 0 dollars. 

Any thoughts or help?

**Comment by RIAEvangelist** [comment]
This is probably related to #85
