### ISSUE TITLE
tipAmount

### ISSUE THREAD

**Issue by PatrickAlphaC** [RIAEvangelist/node-dominos-pizza-api#99]
I've placed a few orders now, and the drivers aren't getting tipped. Are we not sending the tip amount with the card?

**Comment by RIAEvangelist** [comment]
The tip amount is being sent, but I have not done enough testing on the
actual dominos site to confirm how it functions. A lot of their stuff is
quite opaque... I think it is important to add the tip amount to the
payment total as well.

**Comment by RIAEvangelist** [comment]
This issue was closed in #104 PR by @PatrickAlphaC
